config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :coments
  get 'user/index'
  get 'post/index'
  get 'home', to: "home#index"
  get "home", to:"home#about"
  # root "home#about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/add_adress_to_user.rb
class AddAdressToUser < ApplicationRecord
end

app/models/add_comment_ref_coment.rb
class AddCommentRefComent < ApplicationRecord
  belongs_to :photo
end

app/models/add_user_ref_topost.rb
class AddUserRefTopost < ApplicationRecord
  belongs_to :name
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coment.rb
class Coment < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/coments_controller.rb
class ComentsController < ApplicationController
  before_action :set_coment, only: %i[ show edit update destroy ]

  # GET /coments or /coments.json
  def index
    @coments = Coment.all
  end

  # GET /coments/1 or /coments/1.json
  def show
  end

  # GET /coments/new
  def new
    @coment = Coment.new
  end

  # GET /coments/1/edit
  def edit
  end

  # POST /coments or /coments.json
  def create
    @coment = Coment.new(coment_params)

    respond_to do |format|
      if @coment.save
        format.html { redirect_to @coment, notice: "Coment was successfully created." }
        format.json { render :show, status: :created, location: @coment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coments/1 or /coments/1.json
  def update
    respond_to do |format|
      if @coment.update(coment_params)
        format.html { redirect_to @coment, notice: "Coment was successfully updated." }
        format.json { render :show, status: :ok, location: @coment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coments/1 or /coments/1.json
  def destroy
    @coment.destroy
    respond_to do |format|
      format.html { redirect_to coments_url, notice: "Coment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coment
      @coment = Coment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coment_params
      params.fetch(:coment, {})
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
    
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def hello
  end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def index
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coments_helper.rb
module ComentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/coments/_form.html.erb
<%= form_with(model: coment) do |form| %>
  <% if coment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coment.errors.count, "error") %> prohibited this coment from being saved:</h2>

      <ul>
        <% coment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/coments/edit.html.erb
<h1>Editing Coment</h1>

<%= render 'form', coment: @coment %>

<%= link_to 'Show', @coment %> |
<%= link_to 'Back', coments_path %>

app/views/coments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Coments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coments.each do |coment| %>
      <tr>
        <td><%= link_to 'Show', coment %></td>
        <td><%= link_to 'Edit', edit_coment_path(coment) %></td>
        <td><%= link_to 'Destroy', coment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coment', new_coment_path %>

app/views/coments/new.html.erb
<h1>New Coment</h1>

<%= render 'form', coment: @coment %>

<%= link_to 'Back', coments_path %>

app/views/coments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_coment_path(@coment) %> |
<%= link_to 'Back', coments_path %>

app/views/home/about.html.erb
<h1 class="bg-dark text-primary">Hello my name is caleb Buyana</h1>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hellorails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  
  </body>
</html>

app/views/pages/hello.html.erb
<html>

  <h1>Hello rails</h1>
</html>

app/views/post/index.html.erb
<h1>Post#index</h1>
<p>Find me in app/views/post/index.html.erb</p>

app/views/user/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :id %>
    <%= form.text_field :id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.id %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Id:</strong>
  <%= @user.id %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>